# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/HP/Desktop/KGM.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 400)
        MainWindow.setMinimumSize(QtCore.QSize(345, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 490))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_kayitOlustur = QtWidgets.QWidget()
        self.tab_kayitOlustur.setObjectName("tab_kayitOlustur")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_kayitOlustur)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_kayitOlustur)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.radioButton_koBuCihazIcin = QtWidgets.QRadioButton(self.tab_kayitOlustur)
        self.radioButton_koBuCihazIcin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_koBuCihazIcin.setObjectName("radioButton_koBuCihazIcin")
        self.verticalLayout_3.addWidget(self.radioButton_koBuCihazIcin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.radioButton_koFarkliBirCihazIcin = QtWidgets.QRadioButton(self.tab_kayitOlustur)
        self.radioButton_koFarkliBirCihazIcin.setObjectName("radioButton_koFarkliBirCihazIcin")
        self.verticalLayout_3.addWidget(self.radioButton_koFarkliBirCihazIcin)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_koSicilNo = QtWidgets.QLineEdit(self.tab_kayitOlustur)
        self.lineEdit_koSicilNo.setObjectName("lineEdit_koSicilNo")
        self.verticalLayout_2.addWidget(self.lineEdit_koSicilNo)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.pushButton_koUuidAl = QtWidgets.QPushButton(self.tab_kayitOlustur)
        self.pushButton_koUuidAl.setObjectName("pushButton_koUuidAl")
        self.verticalLayout_2.addWidget(self.pushButton_koUuidAl)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.lineEdit_koUUID = QtWidgets.QLineEdit(self.tab_kayitOlustur)
        self.lineEdit_koUUID.setObjectName("lineEdit_koUUID")
        self.verticalLayout_2.addWidget(self.lineEdit_koUUID)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plainTextEdit_koAriza = QtWidgets.QPlainTextEdit(self.tab_kayitOlustur)
        self.plainTextEdit_koAriza.setMinimumSize(QtCore.QSize(300, 180))
        self.plainTextEdit_koAriza.setReadOnly(False)
        self.plainTextEdit_koAriza.setObjectName("plainTextEdit_koAriza")
        self.verticalLayout_5.addWidget(self.plainTextEdit_koAriza)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.pushButton_koKayitOlustur = QtWidgets.QPushButton(self.tab_kayitOlustur)
        self.pushButton_koKayitOlustur.setObjectName("pushButton_koKayitOlustur")
        self.verticalLayout_5.addWidget(self.pushButton_koKayitOlustur)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_kayitOlustur, "")
        self.tab_birimAmiriEkrani = QtWidgets.QWidget()
        self.tab_birimAmiriEkrani.setObjectName("tab_birimAmiriEkrani")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_birimAmiriEkrani)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.tab_birimAmiriEkrani)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.tab_birimAmiriEkrani)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_bbSicilNo = QtWidgets.QLineEdit(self.tab_birimAmiriEkrani)
        self.lineEdit_bbSicilNo.setObjectName("lineEdit_bbSicilNo")
        self.verticalLayout_8.addWidget(self.lineEdit_bbSicilNo)
        self.lineEdit_bbParola = QtWidgets.QLineEdit(self.tab_birimAmiriEkrani)
        self.lineEdit_bbParola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_bbParola.setObjectName("lineEdit_bbParola")
        self.verticalLayout_8.addWidget(self.lineEdit_bbParola)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.pushButton_bbSorgula = QtWidgets.QPushButton(self.tab_birimAmiriEkrani)
        self.pushButton_bbSorgula.setObjectName("pushButton_bbSorgula")
        self.verticalLayout_9.addWidget(self.pushButton_bbSorgula)
        self.plainTextEdit_bbArizalar = QtWidgets.QPlainTextEdit(self.tab_birimAmiriEkrani)
        self.plainTextEdit_bbArizalar.setMinimumSize(QtCore.QSize(300, 180))
        self.plainTextEdit_bbArizalar.setReadOnly(True)
        self.plainTextEdit_bbArizalar.setObjectName("plainTextEdit_bbArizalar")
        self.verticalLayout_9.addWidget(self.plainTextEdit_bbArizalar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_bbSonraki = QtWidgets.QPushButton(self.tab_birimAmiriEkrani)
        self.pushButton_bbSonraki.setObjectName("pushButton_bbSonraki")
        self.horizontalLayout_4.addWidget(self.pushButton_bbSonraki)
        self.pushButton_bbReddet = QtWidgets.QPushButton(self.tab_birimAmiriEkrani)
        self.pushButton_bbReddet.setObjectName("pushButton_bbReddet")
        self.horizontalLayout_4.addWidget(self.pushButton_bbReddet)
        self.pushButton_bbOnayla = QtWidgets.QPushButton(self.tab_birimAmiriEkrani)
        self.pushButton_bbOnayla.setObjectName("pushButton_bbOnayla")
        self.horizontalLayout_4.addWidget(self.pushButton_bbOnayla)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_birimAmiriEkrani, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Karayolları Genel Müdürlüğü Arıza Kayıt"))
        self.label.setText(_translate("MainWindow", "Personel Sicil No:"))
        self.radioButton_koBuCihazIcin.setText(_translate("MainWindow", "Bu cihaz için"))
        self.radioButton_koFarkliBirCihazIcin.setText(_translate("MainWindow", "Farklı bir cihaz için"))
        self.pushButton_koUuidAl.setToolTip(_translate("MainWindow", "<html><head/><body><p>UUID: Bazı anakart üreticilerinin bilgisayarlara tanımladığı eşsiz kimlik. 32 haneden oluşan bu kimliği kendiniz girebilir veya UUID/Sistem Bilgisi Al butonuna basarak eğer destekliyorsa bilgisayarınızın kimlik bilgisini alabilirsiniz. Kimliğin alınamaması durumunda kendiniz de bu veritabanına mahsus bir kimlik tanımlayabilirsiniz.<br/></p></body></html>"))
        self.pushButton_koUuidAl.setText(_translate("MainWindow", "UUID Al"))
        self.pushButton_koKayitOlustur.setText(_translate("MainWindow", "Kayıt Oluştur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kayitOlustur), _translate("MainWindow", "Kayıt Oluştur"))
        self.label_2.setText(_translate("MainWindow", "Birim Amiri / BT Personel Sicil No:"))
        self.label_3.setText(_translate("MainWindow", "Parola:"))
        self.pushButton_bbSorgula.setText(_translate("MainWindow", "Sorgula"))
        self.pushButton_bbSonraki.setText(_translate("MainWindow", "Sonraki"))
        self.pushButton_bbReddet.setText(_translate("MainWindow", "Reddet"))
        self.pushButton_bbOnayla.setText(_translate("MainWindow", "Onayla"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_birimAmiriEkrani), _translate("MainWindow", "Birim Amiri Ekranı / BT Personel"))

